// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apps/lake-governance/lake-catalog/internal/entity"
	"apps/lake-governance/lake-catalog/internal/infra/database"
	"apps/lake-governance/lake-catalog/internal/infra/web/handlers"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func NewWebSchemaCatalogHandler(client *mongo.Client, database2 string) *handlers.WebSchemaCatalogHandler {
	schemaCatalogRepository := database.NewSchemaCatalogRepository(client, database2)
	webSchemaCatalogHandler := handlers.NewWebSchemaCatalogHandler(schemaCatalogRepository)
	return webSchemaCatalogHandler
}

// wire.go:

var setSchemaCatalogRepositoryDependency = wire.NewSet(database.NewSchemaCatalogRepository, wire.Bind(
	new(entity.SchemaCatalogInterface),
	new(*database.SchemaCatalogRepository),
),
)
