// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apps/lake-orchestration/lake-outputs/internal/entity"
	"apps/lake-orchestration/lake-outputs/internal/infra/database"
	"apps/lake-orchestration/lake-outputs/internal/infra/web/handlers"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func NewWebServiceOutputHandler(client *mongo.Client, database2 string) *handlers.WebServiceOutputHandler {
	serviceOutputRepository := database.NewServiceOutputRepository(client, database2)
	webServiceOutputHandler := handlers.NewWebServiceOutputHandler(serviceOutputRepository)
	return webServiceOutputHandler
}

// wire.go:

var setServiceOutputRepositoryDependency = wire.NewSet(database.NewServiceOutputRepository, wire.Bind(
	new(entity.ServiceOutputInterface),
	new(*database.ServiceOutputRepository),
),
)
