swagger: "2.0"
host: "localhost:8002"
basePath: "/"

info:
  description: "Lake Controller API"
  version: "1.0.0"
  title: "Lake Controller API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: fabio.caffarello@gmail.com
    name: Fabio Caffarello

definitions:
  inputDTO.ConfigDTO:
    properties:
      name:
        type: string
      active:
        type: boolean
      frequency:
        type: string
      service:
        type: string
      source:
        type: string
      context:
        type: string
      depends_on:
        type: array
        items:
          type: object
          $ref: "#/definitions/sharedDTO.JobDependencies"
      service_parameters:
        type: object
      source_parameters:
        type: object

  outputDTO.ConfigDTO:
    properties:
      id:
        type: string
      name:
        type: string
      active:
        type: boolean
      frequency:
        type: string
      service:
        type: string
      source:
        type: string
      context:
        type: string
      depends_on:
        type: array
        items:
          type: object
          $ref: "#/definitions/sharedDTO.JobDependencies"
      service_parameters:
        type: object
      source_parameters:
        type: object
      created_at:
        type: string
      updated_at:
        type: string

  inputDTO.ProcessingJobDependenciesDTO:
    properties:
      service:
        type: string
      source:
        type: string
      job_dependencies:
        type: array
        items:
          type: object
          $ref: "#/definitions/sharedDTO.ProcessingJobDependencies"

  outputDTO.ProcessingJobDependenciesDTO:
    properties:
      id:
        type: string
      service:
        type: string
      source:
        type: string
      job_dependencies:
        type: array
        items:
          type: object
          $ref: "#/definitions/sharedDTO.ProcessingJobDependencies"


  sharedDTO.JobDependencies:
    properties:
      service:
        type: string
      source:
        type: string

  sharedDTO.ProcessingJobDependencies:
    properties:
      service:
        type: string
      source:
        type: string
      processing_id:
        type: string
      processing_timestamp:
        type: string
      status_code:
        type: integer


paths:
  /configs:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: config to be created
        required: true
        schema:
          $ref: "#/definitions/inputDTO.ConfigDTO"
      responses:
        "200":
          description: Schema created
          schema:
            $ref: "#/definitions/outputDTO.ConfigDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: List all configs
          schema:
            $ref: "#/definitions/outputDTO.ConfigDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /configs/{id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: Schema id
        required: true
        type: string
      responses:
        "200":
          description: List config by id
          schema:
            $ref: "#/definitions/outputDTO.ConfigDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /configs/service/{service}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: service
        description: config service
        required: true
        type: string
      responses:
        "200":
          description: List all configs by service
          schema:
            $ref: "#/definitions/outputDTO.ConfigDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /configs/service/{service}/source/{source}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: service
        description: Configs service
        required: true
        type: string
      - in: path
        name: source
        description: Configs source
        required: true
        type: string
      responses:
        "200":
          description: List configs by service and source
          schema:
            $ref: "#/definitions/outputDTO.ConfigDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /configs/service/{service}/context/{context}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: service
        description: Configs service
        required: true
        type: string
      - in: path
        name: context
        description: Configs context
        required: true
        type: string
      responses:
        "200":
          description: List configs by service and context
          schema:
            $ref: "#/definitions/outputDTO.ConfigDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /jobs-dependencies:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: job dependencies to be created
        required: true
        schema:
          $ref: "#/definitions/inputDTO.ProcessingJobDependenciesDTO"
      responses:
        "200":
          description: Job dependencies created
          schema:
            $ref: "#/definitions/outputDTO.ProcessingJobDependenciesDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"


  /jobs-dependencies/{id}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: Job dependencies id
        required: true
        type: string
      responses:
        "200":
          description: List job dependencies by id
          schema:
            $ref: "#/definitions/outputDTO.ProcessingJobDependenciesDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

    delete:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: Job dependencies id
        required: true
        type: string
      responses:
        "200":
          description: Job dependencies deleted
          schema:
            $ref: "#/definitions/outputDTO.ProcessingJobDependenciesDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: job dependencies to be created
        required: true
        schema:
          $ref: "#/definitions/inputDTO.ProcessingJobDependenciesDTO"
      responses:
        "200":
          description: Job dependencies created
          schema:
            $ref: "#/definitions/outputDTO.ProcessingJobDependenciesDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

