swagger: "2.0"
host: "localhost:8001"
basePath: "/"

info:
  description: "Lake Gateway API"
  version: "1.0.0"
  title: "Lake Gateway API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: fabio.caffarello@gmail.com
    name: Fabio Caffarello

definitions:
  inputDTO.InputDTO:
    properties:
      data:
        type: object

  inputDTO.InputStatusDTO:
    properties:
      id:
        type: string
      status:
        $ref: "#/definitions/sharedDTO.Status"

  inputDTO.StagingJobDTO:
    properties:
      input_id:
        type: string
      input:
        type: object
      service:
        type: string
      source:
        type: string
      processing_id:
        type: string

  inputDTO.StagingJobIdDTO:
    properties:
      id:
        type: string

  outputDTO.InputDTO:
    properties:
      id:
        type: string
      data:
        type: object
      metadata:
        $ref: "#/definitions/sharedDTO.Metadata"
      status:
        $ref: "#/definitions/sharedDTO.Status"

  outputDTO.StagingJobDTO:
    properties:
      id:
        type: string
      input_id:
        type: string
      input:
        type: object
      service:
        type: string
      source:
        type: string
      processing_id:
        type: string

  sharedDTO.Metadata:
    properties:
      service:
        type: string
      source:
        type: string
      processing_id:
        type: string
      processing_timestamp:
        type: string

  sharedDTO.Status:
    properties:
      code:
        type: integer
      detail:
        type: string

paths:
  /inputs/service/{service}/source/{source}:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: input to be created
        required: true
        schema:
          $ref: "#/definitions/inputDTO.InputDTO"
      - in: path
        name: service
        description: input service
        required: true
        type: string
      - in: path
        name: source
        description: input source
        required: true
        type: string
      responses:
        "200":
          description: input created
          schema:
            $ref: "#/definitions/outputDTO.InputDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: service
        description: input service
        required: true
        type: string
      - in: path
        name: source
        description: input source
        required: true
        type: string
      responses:
        "200":
          description: List all inputs
          schema:
            $ref: "#/definitions/outputDTO.InputDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /inputs/service/{service}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: service
        description: input service
        required: true
        type: string
      responses:
        "200":
          description: List all inputs by service
          schema:
            $ref: "#/definitions/outputDTO.InputDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /inputs/service/{service}/source/{source}/{id}:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: input to be updated
        required: true
        schema:
          $ref: "#/definitions/inputDTO.InputStatusDTO"
      - in: path
        name: service
        description: input service
        required: true
        type: string
      - in: path
        name: source
        description: input source
        required: true
        type: string
      - in: path
        name: id
        description: input id
        required: true
        type: string
      responses:
        "200":
          description: input updated
          schema:
            $ref: "#/definitions/outputDTO.InputDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

    get:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: service
        description: input service
        required: true
        type: string
      - in: path
        name: source
        description: input source
        required: true
        type: string
      - in: path
        name: id
        description: input id
        required: true
        type: string
      responses:
        "200":
          description: List input by id
          schema:
            $ref: "#/definitions/outputDTO.InputDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /staging-jobs:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: staging job to be created
        required: true
        schema:
          $ref: "#/definitions/inputDTO.StagingJobDTO"
      responses:
        "200":
          description: Staging job created
          schema:
            $ref: "#/definitions/outputDTO.StagingJobDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

  /staging-jobs/{id}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: path
        name: id
        description: Staging job id
        required: true
        type: string
      responses:
        "200":
          description: Staging job deleted
          schema:
            $ref: "#/definitions/outputDTO.StagingJobDTO"
        "400":
          description: Bad request
          schema:
            $ref: "#/definitions/handlers.Error"
        "500":
          description: Internal server error
          schema:
            $ref: "#/definitions/handlers.Error"

    /staging-jobs/service/{service}/source/{source}/{id}:
      get:
        consumes:
        - application/json
        produces:
        - application/json
        parameters:
        - in: path
          name: service
          description: Staging job service
          required: true
          type: string
        - in: path
          name: source
          description: Staging job source
          required: true
          type: string
        - in: path
          name: id
          description: Staging job id
          required: true
          type: string
        responses:
          "200":
            description: List staging job by id
            schema:
              $ref: "#/definitions/outputDTO.StagingJobDTO"
          "400":
            description: Bad request
            schema:
              $ref: "#/definitions/handlers.Error"
          "500":
            description: Internal server error
            schema:
              $ref: "#/definitions/handlers.Error"
