
POST http://localhost:8002/configs HTTP/1.1
Content-Type: application/json

{
  "name": "cnep-config",
  "active": true,
  "frequency": "daily",
  "service": "spark-batch",
  "source": "cnep",
  "context": "br",
    "service_parameters": {
      "job_handler": "csv_handler"
    },
    "job_parameters": {
      "url": "https://portaldatransparencia.gov.br/download-de-dados/cnep/{}"
    },
  "depends_on": [
    {"service": "file-unzipper", "source": "cnep"}
  ]
}

###

GET http://localhost:8002/configs HTTP/1.1

###

GET http://localhost:8002/configs/file-downloader-cnep HTTP/1.1

###

GET http://localhost:8002/configs/service/file-downloader HTTP/1.1

###

