
POST http://localhost:8003/schemas HTTP/1.1
Content-Type: application/json

{
  "schema_type": "service-input",
  "service": "spark-batch",
  "source": "cnep",
  "json_schema": {
    "type": "object",
    "properties": {
        "documentUri": {
            "type": "string"
        },
        "partition": {
            "type": "string"
        }
    },
    "required": [
        "documentUri",
        "partition"
    ]
  }
}


###

GET http://localhost:8003/schemas HTTP/1.1

###

GET http://localhost:8003/schemas/service/file-downloader HTTP/1.1

###

GET http://localhost:8003/schemas/input-file-downloader-stocks-file-downloader-stocks HTTP/1.1


###

GET http://localhost:8003/schemas/service/file-downloader/source/ceaf/schema-type/service-input HTTP/1.1
